#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run Prettier to format code
echo "🧹 Running Prettier..."
npx prettier --write --tab-width=2 --use-tabs .

echo "🛠️ Running ESLint fix..."
npx next lint --fix || true
